#!/usr/bin/env zsh
#    _
#   | |__  ___ _ ____      ___ __ ___  _ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#   | |_) \__ \ |_) \ V  V /| | | | | | | | (__
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#             |_|
#

# Needed to access environment variables since bspwm doesn't use the current environment
# Keybindings defined at $DOTS/sxhkd/sxhkdrc
source "$(< ~/.dotdir)/shell/environment.sh"

if [[ ! -d "${MY_RUN}/bspwm" ]]; then
    mkdir "${MY_RUN}/bspwm"
fi

echo '0.5' > "${MY_RUN}/bspwm/preselect-ratio"

typeset CHORD_FIFO="${MY_RUN}/kbchord"
[[ -p "${CHORD_FIFO}" ]] || mkfifo "${CHORD_FIFO}"

pgrep sxhkd &>/dev/null || sxhkd -s "${CHORD_FIFO}" &

# Set name of first desktop
bspc desktop --rename 'init'
echo 'init' > "${MY_RUN}/bspwm/desksets"

# Rules
bspc config external_rules_command "${DOTS}/bspwm/rules_command"

# Placement behavior
bspc config split_ratio '0.5'

# Mouse behavior
bspc config swallow_first_click  'false'
bspc config pointer_modifier     'mod4'
bspc config pointer_action1      'move'
bspc config pointer_action2      'resize_corner'

bspc config normal_border_color  '#111111'
bspc config focused_border_color '#11ab00'

bspc config border_width         5
bspc config window_gap           15

pgrep compton &>/dev/null || compton &
pushd "${DOTS}/bspwm/bar/"; ./bar &; popd

feh --bg-scale "${MY_WALLPAPER}/current"
