#!/usr/bin/env sh

alias xd='xdotool'

declare -r WINDOW_CLASS="$(xprop -id $(xd getactivewindow) \
    | grep 'WM_CLASS' | sed -e 's/^.*, //'               \
    | head -c '-2' | tail -c '+2')"

printf 'Window class:\t%s\n' "$WINDOW_CLASS"

if [[ "$WINDOW_CLASS" == 'Alacritty' ]]; then
    # Acquire the PID of the shell.
    declare -ir pid="$(xprop -id $(xd getactivewindow) | grep '_NET_WM_PID' | sed 's/^.*=//')"

    # Find its current directory.
    declare -r cwd="$(readlink "/proc/$pid/cwd")"

    # Run.
    printf 'Running in directory %s.\n' "$cwd"
    alacritty --working-directory "$cwd"
elif [[ "$WINDOW_CLASS" == 'qutebrowser' ]]; then
    # Easy access to downloads folder
    alacritty --working-directory "$MY_TEMP"
else
    alacritty
fi
